application: app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /.*
  script: main.app
  secure: always

#libraries:
libraries:
- name: ssl
  version: latest
- name: jinja2
  version: latest
